#### 创建数组

有好几种创建数组的方法。
例如，你可以使用array函数从常规的Python列表和元组创造数组。所创建的数组类型由原序列中的元素类型推导而来。

In [1]:
import numpy as np

a = np.array([2,3,4])
print(a)
print(a.dtype)
# 数组将序列包含序列转化成二维的数组，序列包含序列包含序列转化成三维数组等等。
b = np.array([(1.5,2,3),(4,5,6)])
print(b)
# 函数function创建一个全是0的数组，函数ones创建一个全1的数组，函数empty创建一个内容随机并且依赖与内存状态的数组。默认创建的数组类型(dtype)都是float64。
one = np.ones([2,3])
zero = np.zeros([2,3])
empty = np.empty([2,3])
print(one,zero,empty)
print("=========")
#为了创建一个数列，NumPy提供一个类似arange的函数返回数组而不是列表:
arange = np.arange(2,20,2)
print(arange)
a_reshape = arange.reshape(3,3) #不改变原始数组的shape
arange.resize(3,3)# 改变原始数组的shape
print(a_reshape)
print(arange)
print(arange.reshape([-1]))
# 当arange使用浮点数参数时，由于有限的浮点数精度，通常无法预测获得的元素个数 使用函数linspace去接收我们想要的元素个数来代替用range来指定步长。
a_lin = np.linspace(0,np.pi,3)
print(a_lin)

[2 3 4]
int32
[[ 1.5  2.   3. ]
 [ 4.   5.   6. ]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]] [[ 0.  0.  0.]
 [ 0.  0.  0.]] [[  1.13684362e-311   1.13682325e-311   1.13684367e-311]
 [  1.13684388e-311   1.13684294e-311   1.13682384e-311]]
[ 2  4  6  8 10 12 14 16 18]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[ 2  4  6  8 10 12 14 16 18]
[ 0.          1.57079633  3.14159265]


#### 索引，切片和迭代
一维数组可以被索引、切片和迭代，就像列表和其它Python序列。

In [10]:
a_slice = np.arange(10)**2
print(a_slice)
print(a_slice[2:5])# 不包括最后一个
print(a_slice[:-1])# -1代表最后一个索引
print(a_slice[:])
print(a_slice[:10:2]) #从0开始到10 步长为2
print(a_slice[::-1]) # 倒序

[ 0  1  4  9 16 25 36 49 64 81]
[ 4  9 16]
[ 0  1  4  9 16 25 36 49 64]
[ 0  1  4  9 16 25 36 49 64 81]
[ 0  4 16 36 64]
[81 64 49 36 25 16  9  4  1  0]


#### 多维数组可以每个轴有一个索引。这些索引由一个逗号分割的元组给出。

In [19]:
def f(x,y):
    return 10*x + y
arr = np.fromfunction(f,(5,4),dtype = np.int32) # 输出5行4列二维数组
print(arr)
print(arr[2,3])#取第2行第3列的元素
print(arr.shape)
print(arr[0:5,1]) # 取0到5行的第1列元素 返回数组 即第1列向量
print(arr[-1,1]) #最后一行
print(arr[:-1,1]) # 0到最后一行

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23
(5, 4)
[ 1 11 21 31 41]
41
[ 1 11 21 31]


#### 当少于轴数的索引被提供时，确失的索引被认为是整个切片：
 b[i]中括号中的表达式被当作i和一系列:，来代表剩下的轴。NumPy也允许你使用“点”像b[i,...]。

点(…)代表许多产生一个完整的索引元组必要的分号。如果x是秩为5的数组(即它有5个轴)，那么:

x[1,2,…] 等同于 x[1,2,:,:,:],
x[…,3] 等同于 x[:,:,:,:,3]
x[4,…,5,:] 等同 x[4,:,:,5,:].


In [26]:
print(arr[-1])
print(arr[-1,...])
# 迭代多维数组是就第一个轴而言的:
for row in arr:
    print(row) # 打印每一行
# 想对每个数组中元素进行运算，我们可以使用flat属性，该属性是数组元素的一个迭代器
for element in arr.flat:
    print(element)

[40 41 42 43]
[40 41 42 43]
[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]
0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


#### 形状操作
一个数组的形状由它每个轴上的元素个数给出

In [27]:
arr = np.floor(np.random.random((3,4)))
print(arr)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
