#### 创建数组

有好几种创建数组的方法。
例如，你可以使用array函数从常规的Python列表和元组创造数组。所创建的数组类型由原序列中的元素类型推导而来。

In [12]:
import numpy as np

a = np.array([2,3,4])
print(a)
print(a.dtype)
# 数组将序列包含序列转化成二维的数组，序列包含序列包含序列转化成三维数组等等。
b = np.array([(1.5,2,3),(4,5,6)])
print(b)
# 函数function创建一个全是0的数组，函数ones创建一个全1的数组，函数empty创建一个内容随机并且依赖与内存状态的数组。默认创建的数组类型(dtype)都是float64。
one = np.ones([2,3])
zero = np.zeros([2,3])
empty = np.empty([2,3])
print(one,zero,empty)
print("=========")
#为了创建一个数列，NumPy提供一个类似arange的函数返回数组而不是列表:
arange = np.arange(2,20,2)
print(arange)
a_reshape = arange.reshape(3,3) #不改变原始数组的shape
arange.resize(3,3)# 改变原始数组的shape
print(a_reshape)
print(arange)
print(a)

[2 3 4]
int32
[[ 1.5  2.   3. ]
 [ 4.   5.   6. ]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]] [[ 0.  0.  0.]
 [ 0.  0.  0.]] [[ 1.5  2.   3. ]
 [ 4.   5.   6. ]]
[ 2  4  6  8 10 12 14 16 18]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
None
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
