#### 创建数组

有好几种创建数组的方法。
例如，你可以使用array函数从常规的Python列表和元组创造数组。所创建的数组类型由原序列中的元素类型推导而来。

In [1]:
import numpy as np

a = np.array([2,3,4])
print(a)
print(a.dtype)
# 数组将序列包含序列转化成二维的数组，序列包含序列包含序列转化成三维数组等等。
b = np.array([(1.5,2,3),(4,5,6)])
print(b)
# 函数function创建一个全是0的数组，函数ones创建一个全1的数组，函数empty创建一个内容随机并且依赖与内存状态的数组。默认创建的数组类型(dtype)都是float64。
one = np.ones([2,3])
zero = np.zeros([2,3])
empty = np.empty([2,3])
print(one,zero,empty)
print("=========")
#为了创建一个数列，NumPy提供一个类似arange的函数返回数组而不是列表:
arange = np.arange(2,20,2)
print(arange)
a_reshape = arange.reshape(3,3) #不改变原始数组的shape
arange.resize(3,3)# 改变原始数组的shape
print(a_reshape)
print(arange)
print(arange.reshape([-1]))
# 当arange使用浮点数参数时，由于有限的浮点数精度，通常无法预测获得的元素个数 使用函数linspace去接收我们想要的元素个数来代替用range来指定步长。
a_lin = np.linspace(0,np.pi,3)
print(a_lin)

[2 3 4]
int32
[[ 1.5  2.   3. ]
 [ 4.   5.   6. ]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]] [[ 0.  0.  0.]
 [ 0.  0.  0.]] [[  9.95159263e-312   9.95201055e-312   9.95180538e-312]
 [  9.95162919e-312   9.95200728e-312   9.95159219e-312]]
[ 2  4  6  8 10 12 14 16 18]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[ 2  4  6  8 10 12 14 16 18]
[ 0.          1.57079633  3.14159265]


#### 索引，切片和迭代
一维数组可以被索引、切片和迭代，就像列表和其它Python序列。

In [3]:
a_slice = np.arange(10)**2
print(a_slice)
print(a_slice[2:5])# 不包括最后一个
print(a_slice[:-1])# -1代表最后一个索引
print(a_slice[:])
print(a_slice[:10:2]) #从0开始到10 步长为2
print(a_slice[::-1]) # 倒序

[ 0  1  4  9 16 25 36 49 64 81]
[ 4  9 16]
[ 0  1  4  9 16 25 36 49 64]
[ 0  1  4  9 16 25 36 49 64 81]
[ 0  4 16 36 64]
[81 64 49 36 25 16  9  4  1  0]


#### 多维数组可以每个轴有一个索引。这些索引由一个逗号分割的元组给出。

In [4]:
def f(x,y):
    return 10*x + y
arr = np.fromfunction(f,(5,4),dtype = np.int32) # 输出5行4列二维数组
print(arr)
print(arr[2,3])#取第2行第3列的元素
print(arr.shape)
print(arr[0:5,1]) # 取0到5行的第1列元素 返回数组 即第1列向量
print(arr[-1,1]) #最后一行
print(arr[:-1,1]) # 0到最后一行

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23
(5, 4)
[ 1 11 21 31 41]
41
[ 1 11 21 31]


#### 当少于轴数的索引被提供时，确失的索引被认为是整个切片：
 b[i]中括号中的表达式被当作i和一系列:，来代表剩下的轴。NumPy也允许你使用“点”像b[i,...]。

点(…)代表许多产生一个完整的索引元组必要的分号。如果x是秩为5的数组(即它有5个轴)，那么:

x[1,2,…] 等同于 x[1,2,:,:,:],
x[…,3] 等同于 x[:,:,:,:,3]
x[4,…,5,:] 等同 x[4,:,:,5,:].


In [5]:
print(arr[-1])
print(arr[-1,...])
# 迭代多维数组是就第一个轴而言的:
for row in arr:
    print(row) # 打印每一行
# 想对每个数组中元素进行运算，我们可以使用flat属性，该属性是数组元素的一个迭代器
for element in arr.flat:
    print(element)

[40 41 42 43]
[40 41 42 43]
[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]
0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


#### 形状操作
一个数组的形状由它每个轴上的元素个数给出

In [7]:
arr = np.floor(10*np.random.random((3,4)))
print(arr)

[[ 9.  9.  0.  1.]
 [ 8.  8.  9.  7.]
 [ 3.  1.  3.  2.]]


#### 线性代数

简单数组运算
参考numpy文件夹中的linalg.py获得更多信息

In [21]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print(a)
print(np.transpose(a))
print(np.linalg.inv(a))#矩阵a的逆矩阵
print(np.linalg.det(a))
print(np.linalg.eig(a))#矩阵a的特征值和特征向量
#矩阵类
m = np.matrix('1.0 2.0; 3.0 4.0')
print(m)
print("====")
print(m[0,1])

[[ 1.  2.]
 [ 3.  4.]]
[[ 1.  3.]
 [ 2.  4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0
(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
[[ 1.  2.]
 [ 3.  4.]]
====
2.0


#### “自动”改变形状

更改数组的维度，你可以省略一个尺寸，它将被自动推导出来。

In [26]:
a = np.arange(30)
print(a)
a.shape = 3,-1 #-1可以自动推到计算
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


#### 直方图(histogram)

NumPy中histogram函数应用到一个数组返回一对变量：直方图数组和箱式向量。注意：matplotlib也有一个用来建立直方图的函数(叫作hist,正如matlab中一样)与NumPy中的不同。主要的差别是pylab.hist自动绘制直方图，而numpy.histogram仅仅产生数据。

In [29]:
mu,sigma = 2,0.5
v = np.random.normal(mu,sigma,10)
print(v)

[ 2.38011539  1.96878428  2.23963444  1.05296944  1.8394844   2.34113435
  1.37616676  1.66713676  1.87501206  2.07485644]


In [34]:
#结构数组
'''
我们先创建一个dtype对象persontype，通过其字典参数描述结构类型的各个字段。字典有两个关键字：names，formats。每个关键字对应的值都是一个列表。names定义结构中的每个字段名，而formats则定义每个字段的类型：

    S32 : 32个字节的字符串类型，由于结构中的每个元素的大小必须固定，因此需要指定字符串的长度
    i : 32bit的整数类型，相当于np.int32
    f : 32bit的单精度浮点数类型，相当于np.float32
'''
import time
print(time.clock())
persontype = np.dtype({
    'names':['name', 'age', 'weight'],
    'formats':['S2','i', 'f']})
a = np.array([("Zhang",32,75.5),("Wang",24,65.2)],dtype=persontype)
print(time.clock())
print(a)

17.824940342549233
17.825333889280902
[(b'Zh', 32, 75.5) (b'Wa', 24, 65.19999694824219)]


#### dot点积 : 
对于两个一维的数组，计算的是这两个数组对应下标元素的乘积和(数学上称之为内积)；对于二维数组，计算的是两个数组的矩阵乘积；对于多维数组，它的通用计算公式如下，即结果数组中的每个元素都是：数组a的最后一维上的所有元素与数组b的倒数第二位上的所有元素的乘积和：

In [14]:
a = np.arange(12).reshape(2,3,2)
b = np.arange(12,24).reshape(2,2,3)
c = np.dot(a,b)


print(a.reshape(-1))
print("========")
print(b)
print("========")
print(c,c.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]
[[[[ 15  16  17]
   [ 21  22  23]]

  [[ 69  74  79]
   [ 99 104 109]]

  [[123 132 141]
   [177 186 195]]]


 [[[177 190 203]
   [255 268 281]]

  [[231 248 265]
   [333 350 367]]

  [[285 306 327]
   [411 432 453]]]] (2, 3, 2, 3)


#### inner 内积: 
和dot乘积一样，对于两个一维数组，计算的是这两个数组对应下标元素的乘积和；对于多维数组，它计算的结果数组中的每个元素都是：数组a和b的最后一维的内积
- 因此数组a和b的最后一维的长度必须相同：

In [15]:
a = np.arange(12).reshape(2,3,2)
b = np.arange(12,24).reshape(2,3,2)
c = np.inner(a,b)
print(a)
print("========")
print(b)
print("========")
print(c,c.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
[[[[ 13  15  17]
   [ 19  21  23]]

  [[ 63  73  83]
   [ 93 103 113]]

  [[113 131 149]
   [167 185 203]]]


 [[[163 189 215]
   [241 267 293]]

  [[213 247 281]
   [315 349 383]]

  [[263 305 347]
   [389 431 473]]]] (2, 3, 2, 3)


#### outer外积 : 
     只按照一维数组进行计算，如果传入参数是多维数组，则先将此数组展平为一维数组之后再进行运算。outer乘积计算的列向量和行向量的矩阵乘积：

In [18]:
d = np.outer(a,b)
print(d,d.shape)
print(np.outer([1,2,3],[4,5,6,7]))

[[  0   0   0   0   0   0   0   0   0   0   0   0]
 [ 12  13  14  15  16  17  18  19  20  21  22  23]
 [ 24  26  28  30  32  34  36  38  40  42  44  46]
 [ 36  39  42  45  48  51  54  57  60  63  66  69]
 [ 48  52  56  60  64  68  72  76  80  84  88  92]
 [ 60  65  70  75  80  85  90  95 100 105 110 115]
 [ 72  78  84  90  96 102 108 114 120 126 132 138]
 [ 84  91  98 105 112 119 126 133 140 147 154 161]
 [ 96 104 112 120 128 136 144 152 160 168 176 184]
 [108 117 126 135 144 153 162 171 180 189 198 207]
 [120 130 140 150 160 170 180 190 200 210 220 230]
 [132 143 154 165 176 187 198 209 220 231 242 253]] (12, 12)
[[ 4  5  6  7]
 [ 8 10 12 14]
 [12 15 18 21]]
