In [1]:
# This function introduces various ways to create
# tensors in Tensorflow
import tensorflow as tf
from tensorflow.python.framework import ops

ops.reset_default_graph()
# Introduce tensors in tf
# Get graph handle
sess = tf.Session()
print(sess)


In [4]:
my_tensor = tf.zeros([1,20])
my_tensor_ini = tf.zeros_initializer()
#my_tensor_like = tf.zeros_like()
print(my_tensor)
print(my_tensor_ini)
#print(my_tensor_like)

Tensor("zeros_2:0", shape=(1, 20), dtype=float32)


In [5]:
# Declare a variable
my_var = tf.Variable(tf.zeros([1,20]))
# Different kinds of variables
row_dim = 2
col_dim = 3
# Zero initialized variable
zero_var = tf.Variable(tf.zeros([row_dim,col_dim]))
# One initialized variable
one_var = tf.Variable(tf.ones([row_dim,col_dim]))
print(my_var)
print(zero_var)
print(one_var)


<tf.Variable 'Variable:0' shape=(1, 20) dtype=float32_ref>
<tf.Variable 'Variable_1:0' shape=(2, 3) dtype=float32_ref>
<tf.Variable 'Variable_2:0' shape=(2, 3) dtype=float32_ref>


In [9]:
# shaped like other variable
sess.run(zero_var.initializer)
sess.run(one_var.initializer)

In [10]:
zero_similar = tf.Variable(tf.zeros_like(zero_var))
ones_similar = tf.Variable(tf.ones_like(one_var))
print(zero_similar)
print(ones_similar)

<tf.Variable 'Variable_3:0' shape=(2, 3) dtype=float32_ref>
<tf.Variable 'Variable_4:0' shape=(2, 3) dtype=float32_ref>


In [16]:
# Fill shape with a constant
fill_var = tf.Variable(tf.fill([row_dim,col_dim],-1))
# Create a variable from a constant
const_var = tf.Variable(tf.constant([1,2,3,4,5,6,7]))
# This can also be used to fill an array:
const_fill_var = tf.Variable(tf.constant(-1,shape=[row_dim,col_dim]))
# Sequence generation
linear_var = tf.Variable(tf.linspace(start=0.0,stop=1.0,num=3))# Generates [0.0, 0.5, 1.0] includes the end
sequence_var = tf.Variable(tf.range(start=6,limit=15,delta=3))# Generates [6, 9, 12] doesn't include the end
# Random Normal
rnorm_var = tf.random_normal([row_dim,col_dim],mean=0.0,stddev=1.0)

In [26]:
# Initialize operation
initialize_op = tf.global_variables_initializer()
# merged = tf.merge_all_summaries()
# Run initialization of variable
sess.run(initialize_op)
print(sess.run(const_var))
print(sess.run(const_fill_var))

[1 2 3 4 5 6 7]
[[-1 -1 -1]
 [-1 -1 -1]]


In [23]:
# Using Placeholders
import numpy as np
x = tf.placeholder(tf.float32,shape=(4,4))
y = tf.identity(x)
rand_array = np.random.rand(4,4)
print(sess.run(y,feed_dict={x:rand_array}))





[[ 0.08466251  0.75764555  0.03826912  0.07103471]
 [ 0.7834745   0.56204587  0.17192082  0.78158969]
 [ 0.96857929  0.51628798  0.50791281  0.40980497]
 [ 0.8227039   0.36286679  0.70083344  0.78929722]]
