In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.python.framework import ops

In [19]:
ops.reset_default_graph()
sess = tf.Session()
# declar matric
# Identity matrix
diag_matric = tf.diag([1.0,1.0,1.0])
print(sess.run(diag_matric))
print(diag_matric)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
Tensor("Diag:0", shape=(3, 3), dtype=float32)


In [20]:
# 2x3 random norm matrix
A = tf.truncated_normal([2,3])
print(sess.run(A))
print(A)

[[-0.06304682 -1.71348524 -0.94842297]
 [ 0.59229612  0.70525706 -0.15591498]]
Tensor("truncated_normal:0", shape=(2, 3), dtype=float32)


In [4]:
# 2x3 constant matrix
B = tf.fill([2,3],5.0)
print(sess.run(B))

[[ 5.  5.  5.]
 [ 5.  5.  5.]]


In [24]:
# 3x2 random uniform matrix
C = tf.random_uniform([2,3])
print(sess.run(C))
print("different matric:")
print(sess.run(C))
print(C)

[[ 0.27585018  0.3143152   0.60240805]
 [ 0.86997807  0.87589324  0.03087676]]
different matric:
[[ 0.86396742  0.6052146   0.06493902]
 [ 0.08311319  0.62800026  0.31784022]]
Tensor("random_uniform:0", shape=(2, 3), dtype=float32)


In [25]:
# Create matrix from np array
D = tf.convert_to_tensor(np.array([[1.0,2.0,3.0],[4.0,5.0,6.0],[-4.0,-3.0,-4.0]]))
E = tf.convert_to_tensor(np.random.rand(4,4))
print(sess.run(D))
print(sess.run(E))
print(E)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [-4. -3. -4.]]
[[ 0.7611366   0.84503726  0.39926276  0.11731382]
 [ 0.64482661  0.66011195  0.97323603  0.56121759]
 [ 0.54152724  0.41102893  0.34500535  0.02907484]
 [ 0.6555299   0.57453317  0.92093235  0.3535125 ]]
Tensor("Const_3:0", shape=(4, 4), dtype=float64)


In [10]:
# Matrix addition/subtraction
print(sess.run(A + B))
print(sess.run(A - B))


[[ 5.4021163   6.1506381   4.58586788]
 [ 5.17422962  4.26944447  4.72785091]]
[[-5.1673336  -6.52105141 -5.13930273]
 [-5.80337095 -4.42917347 -4.25841999]]


In [29]:
# Matrix Multiplication
print(sess.run(tf.matmul(C,diag_matric)))
# Matrix Transpose
print(sess.run(tf.transpose(D)))
# Matrix Determinant
print(sess.run(tf.matrix_determinant(D)))


[[ 0.11830235  0.00547576  0.3335979 ]
 [ 0.78032529  0.84384966  0.90598917]]
[[ 1.  4. -4.]
 [ 2.  5. -3.]
 [ 3.  6. -4.]]
6.0


In [40]:
# Matrix Inverse
D_inverse = sess.run(tf.matrix_inverse(diag_matric))
print(D_inverse)
# print(sess.run(tf.matrix_determinant(D_inverse))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [44]:
# Cholesky Decomposition
print(sess.run(tf.cholesky(diag_matric)))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [46]:
# Eigenvalues and Eigenvectors
print(sess.run(tf.self_adjoint_eigvals(diag_matric)))

[ 1.  1.  1.]
